name: hello_world_dart
private: True # let's not accidentally publish this to pub.dartlang.org
description: >-
  Hello world server example in dart.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  shelf: ^0.7.3
